# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b15baeffb5c02310c1e6518d82144a03b4e2d260d61266301ae4993ae49255343abe159b24555629713c1d0f8b856380623813d9cb808a9afff17318998461df

test:
  secret_key_base: b8872c0b3eeb8bec920809525f83df56943c650b160b9d35657a3f4910114b532f4bfccf5d43bd1aa0b161acf532f354182dadae3d388b944b69afe7760d35ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
